# Generated by Django 4.2.11 on 2026-03-23 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employee_hora_entrada_employee_hora_salida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_llegada', models.TimeField(verbose_name='Hora de llegada real')),
                ('minutos_tarde', models.PositiveIntegerField(default=0, verbose_name='Minutos de retraso')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento aplicado')),
                ('period', models.IntegerField(choices=[(1, 'Primera quincena (1–15)'), (2, 'Segunda quincena (16–fin)')], verbose_name='Quincena')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_arrivals', to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Llegada tarde',
                'verbose_name_plural': 'Llegadas tarde',
                'db_table': 'late_arrivals',
                'ordering': ['-fecha'],
                'unique_together': {('employee', 'fecha')},
            },
        ),
    ]
