# Generated by Django 4.2.11 on 2026-03-14 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de nómina')),
                ('period', models.IntegerField(choices=[(1, 'Primera quincena (1–15)'), (2, 'Segunda quincena (16–fin)')], verbose_name='Período')),
                ('salary_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario base')),
                ('vacation_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pago vacaciones')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonos')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deducciones')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total a pagar')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'db_table': 'payroll',
                'ordering': ['-date', '-period'],
                'unique_together': {('employee', 'date', 'period')},
            },
        ),
    ]
