# Generated by Django 5.0.1 on 2026-03-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrecord',
            name='bonuses',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='deductions',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='dias_laborados',
            field=models.PositiveIntegerField(default=15, verbose_name='Días laborados'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='otras_deducciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Otras deducciones'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='prestamo_adelanto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deduc. Préstamo/Adelanto'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sub-total devengado'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='viatico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Viático'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='salary_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario ordinario'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total devengado'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='vacation_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vacaciones'),
        ),
    ]
