# Generated by Django 4.2.11 on 2026-03-15 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_payrollrecord_bonuses_and_more'),
        ('payroll', '0003_add_descuento_faltas'),
    ]

    operations = [
    ]
