# Generated by Django 4.2.11 on 2026-03-14 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.PositiveIntegerField(default=0, verbose_name='Días totales')),
                ('used_days', models.PositiveIntegerField(default=0, verbose_name='Días usados')),
                ('vacation_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pago por día de vacaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacation', to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Vacaciones',
                'verbose_name_plural': 'Vacaciones',
                'db_table': 'vacations',
            },
        ),
    ]
