# Generated by Django 4.2.11 on 2026-03-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0004_vacation_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='dias_falta_q1',
            field=models.PositiveIntegerField(default=0, verbose_name='Faltas en Q1'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='dias_falta_q2',
            field=models.PositiveIntegerField(default=0, verbose_name='Faltas en Q2'),
        ),
        migrations.AlterField(
            model_name='vacationabsence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
