# Generated by Django 4.2.11 on 2026-03-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('position', models.CharField(max_length=100, verbose_name='Puesto')),
                ('salary_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario base quincenal')),
                ('hire_date', models.DateField(verbose_name='Fecha de contratación')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'employees',
                'ordering': ['name'],
            },
        ),
    ]
