# Generated by Django 5.0.1 on 2026-03-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
    ]
