# Generated by Django 4.2.11 on 2026-03-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_cedula_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de entrada'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
        migrations.AddField(
            model_name='employee',
            name='horas_por_dia',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Horas laborales por día'),
        ),
    ]
